### ISSUE TITLE
`require': cannot load such file -- gem-miner/cli

### ISSUE THREAD

**Issue by dunyakirkali** [reevoo/gem-miner#8]
I'm trying to get this to work under `ruby-2.2.2` installed via `rvm` on a Mac `Version10.11 (15A284)`.

Any ideas?

**Comment by jonnyarnold** [comment]
I've verified this doesn't work on my machine. Let me see if I can fix it...

**Comment by jonnyarnold** [comment]
I had to reinstall the gem before it worked...

```
gem uninstall gem-miner
gem install gem-miner
```

Can you see what happens when you do this?

If it doesn't work, can you send the output to `gem open gem-miner`?

**Comment by jonnyarnold** [comment]
I've got a few bugfixes added to v1.0.1, so you might want to try that too.

**Comment by dunyakirkali** [comment]
I have installed v1.0.1 and I unfortunately I still get the same error.
Please let me know if I can do anything to help u out debugging it.

**Comment by jonnyarnold** [comment]
Could you check `gem open gem-miner` and look for the cli.rb in `<Gem Directory>/lib/gem-miner/cli.rb`? When I first installed from RubyGems, I got an old version that didn't have this file.

Here's my console output:

```
➜  ~  gem uninstall gem-miner
Remove executables:
    gem-miner

in addition to the gem? [Yn]  Y
Removing gem-miner
Successfully uninstalled gem-miner-1.0.0
➜  ~  gem install gem-miner
Fetching: gem-miner-1.0.1.gem (100%)
Successfully installed gem-miner-1.0.1
Parsing documentation for gem-miner-1.0.1
Installing ri documentation for gem-miner-1.0.1
Done installing documentation for gem-miner after 0 seconds
1 gem installed
➜  ~  gem-miner
Commands:
  gem-miner gems QUERY      # Collects all gems for projects given by the Git...
  gem-miner help [COMMAND]  # Describe available commands or one specific com...
```

Let me know if you get any different!

**Comment by dunyakirkali** [comment]
This is really weird. Here is my output:

```
± % gem uninstall gem-miner
Remove executables:
    gem-miner

in addition to the gem? [Yn]  Y
Removing gem-miner
Successfully uninstalled gem-miner-1.0.1

± % gem install gem-miner
Fetching: gem-miner-1.0.1.gem (100%)
Successfully installed gem-miner-1.0.1
Parsing documentation for gem-miner-1.0.1
Installing ri documentation for gem-miner-1.0.1
Done installing documentation for gem-miner after 0 seconds
1 gem installed

± % gem-miner
/Users/dunyakirkali/.rvm/gems/ruby-2.2.2/gems/gem-miner-1.0.1/exe/gem-miner:4:in `require': cannot load such file -- gem-miner/cli (LoadError)
    from /Users/dunyakirkali/.rvm/gems/ruby-2.2.2/gems/gem-miner-1.0.1/exe/gem-miner:4:in `<top (required)>'
    from /Users/dunyakirkali/.rvm/gems/ruby-2.2.2/bin/gem-miner:23:in `load'
    from /Users/dunyakirkali/.rvm/gems/ruby-2.2.2/bin/gem-miner:23:in `<main>'
    from /Users/dunyakirkali/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
    from /Users/dunyakirkali/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
```

I did open the gem using `gem open gem-miner` and I do have the `<Gem Directory>/lib/gem-miner/cli.rb` file in place. Weird :S

**Comment by jonnyarnold** [comment]
So I've had a chat with @Antti here and we wonder whether it's an issue with RVM; we're using rbenv here.

My knowledge of RVM is not very good, so I can't be a lot of help here. I imagine I'll have to add the `gem-miner` directory to the load path...?

**Comment by dunyakirkali** [comment]
I'll give it a try on rbenv and let u know of my findings.

**Comment by dunyakirkali** [comment]
Doesn't look like an rbenv issue

```
$ rbenv -v
rbenv 0.4.0-153-g3b6faa8

$ gem list gem-miner

*** LOCAL GEMS ***

gem-miner (1.0.1)

$ gem-miner
/home/deployer/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/gem-miner-1.0.1/exe/gem-miner:4:in `require': cannot load such file -- gem-miner/cli (LoadError)
    from /home/deployer/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/gem-miner-1.0.1/exe/gem-miner:4:in `<top (required)>'
    from /home/deployer/.rbenv/versions/2.2.2/bin/gem-miner:23:in `load'
    from /home/deployer/.rbenv/versions/2.2.2/bin/gem-miner:23:in `<main>'
```

**Comment by richardbatty** [comment]
It isn't rvm as it doesn't work on my machine, even after reinstall, and I'm on rbenv. Isn't it a problem with the require in https://github.com/reevoo/gem-miner/blob/master/exe/gem-miner line 4?

**Comment by dunyakirkali** [comment]
@richardbatty that's where the error comes from

**Comment by mikekr1** [comment]
Yup, same thing happens for me in 2.2.2, works fine in 2.1.0.

**Comment by dunyakirkali** [comment]
@shyvy88  Interesting.

**Comment by mikekr1** [comment]
Also broken in 2.2.3

**Comment by dunyakirkali** [comment]
I can confirm that it works on `ruby-2.1.0`

**Comment by mikekr1** [comment]
We've figured it out, thanks to @Antti . Fix incoming

**Comment by jonnyarnold** [comment]
@dunyakirkali - Thanks for the bug report. It looks like the call to `require bundler/setup` in the exe was causing the sadness. This has been removed in v1.0.2.

Can you `gem uninstall gem-miner`, `gem install gem-miner` and `gem-miner` and let me know if it addresses the issue?

**Comment by jonnyarnold** [comment]
(And thanks to @Antti for finding this!)

**Comment by dunyakirkali** [comment]
@Antti @shyvy88 Good job guys! It works :)
